### PR TITLE
#44 Scroll position preserved when opening a ticket view and going back to the tickets list

### PR DESCRIPTION
**Pull request by mPastuszko**

### CODE REVIEW

**Comment by molszanski** [comment]
@mPastuszko hi there! Just saw the PR 🤦 
can u fix conflicts? Or I can just copy paste code to a new place

**Comment by mPastuszko** [comment]
@molszanski Hi! Sure, better if you copy-paste (plus improve the code if necessary). I'm not a professional front-end dev and did my best to fix the issue. Feel free to do whatever is best to improve your great website :) After that, you can close #44.

BTW I also reported #45 but wasn't able to develop a solution for that. For you, it will be probably much easier to implement it.

**Comment by molszanski** [comment]
@mPastuszko We've fixed the scroll issue! Thanks for pointing it out <3

**Comment by molszanski** [comment]
We will solve location by adding map airbnb style soon <3

**Comment by mPastuszko** [comment]
Awesome, thanks for your quick reaction and good luck with further development! 💪

**Comment by PokerTuna** [comment]
> Awesome, thanks for your quick reaction and good luck with further development! 💪

thanks man! If u have any more ideas, feel free to contribute :)

**Comment by PokerTuna** [comment]
@mPastuszko fix is on main, closing this PR - thanks! 🙌

**Pull request closed without merging**
